import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class AdviserAccountsScreen extends StatefulWidget {
  final String orgId, orgName;
  const AdviserAccountsScreen({super.key, required this.orgId, required this.orgName});
  @override State<AdviserAccountsScreen> createState() => _AdviserAccountsScreenState();
}
class _AdviserAccountsScreenState extends State<AdviserAccountsScreen> {
  static const green=Color(0xFF16A34A), dark=Color(0xFF12352A), muted=Color(0xFF6B8178), bg=Color(0xFFF3FAF5);
  final db=Supabase.instance.client; bool loading=true; List<Map<String,dynamic>> members=[];
  @override void initState(){super.initState();load();}
  Future<void> load() async {if(mounted)setState(()=>loading=true);try{final r=await db.from('members').select('id,name,position,profile_id,profiles(id,name,email,role,active,avatar_url,student_id)').eq('org_id',widget.orgId).order('name');if(!mounted)return;setState(()=>members=List<Map<String,dynamic>>.from(r as List));}catch(e){if(mounted)_snack('Could not load accounts: $e',true);}finally{if(mounted)setState(()=>loading=false);}}
  Future<void> changeRole(Map<String,dynamic> m,String role) async {final p=m['profiles'];if(p is! Map||p['id']==null){_snack('This member is not linked to a login account.',true);return;}final name=p['name']?.toString().isNotEmpty==true?p['name'].toString():m['name']?.toString()??'Member';final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:Text(role=='officer'?'Make Officer?':'Return to Student?'),content:Text(role=='officer'?'$name will keep the same Gmail and access the Officer dashboard for ${widget.orgName}.':'$name will return to the Student dashboard while keeping the organization membership.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(style:FilledButton.styleFrom(backgroundColor:green),onPressed:()=>Navigator.pop(c,true),child:Text(role=='officer'?'Make Officer':'Return to Student'))]));if(ok!=true)return;try{await db.from('profiles').update({'role':role,'assigned_org_id':role=='officer'?widget.orgId:null}).eq('id',p['id'].toString());await db.from('members').update({'position':role=='officer'?'Officer':'Member'}).eq('id',m['id'].toString()).eq('org_id',widget.orgId);_snack(role=='officer'?'$name is now an Officer.':'$name is now a Student again.');await load();}catch(e){_snack('Could not change role: $e',true);}}
  void _snack(String s,[bool err=false]){if(!mounted)return;ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s),backgroundColor:err?Colors.red.shade700:green,behavior:SnackBarBehavior.floating));}
  @override Widget build(BuildContext context){final officers=members.where((m){final p=m['profiles'];return p is Map&&p['role']=='officer';}).length;return Scaffold(backgroundColor:bg,appBar:AppBar(backgroundColor:green,foregroundColor:Colors.white,elevation:0,title:const Text('Organization Accounts',style:TextStyle(fontWeight:FontWeight.w800)),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh_rounded))]),body:loading?const Center(child:CircularProgressIndicator(color:green)):RefreshIndicator(color:green,onRefresh:load,child:ListView(padding:const EdgeInsets.fromLTRB(18,18,18,30),children:[Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:const LinearGradient(colors:[green,Color(0xFF0F766E)]),borderRadius:BorderRadius.circular(24)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('ACCOUNT MANAGEMENT',style:TextStyle(color:Colors.white70,fontSize:11,fontWeight:FontWeight.w800)),const SizedBox(height:6),Text(widget.orgName,style:const TextStyle(color:Colors.white,fontSize:23,fontWeight:FontWeight.w900)),const SizedBox(height:5),const Text('Promote members to officers using their existing accounts.',style:TextStyle(color:Colors.white70)),const SizedBox(height:18),Row(children:[_sum('${members.length-officers}','Students'),_sum('$officers','Officers'),_sum('${members.length}','Members')])])),const SizedBox(height:16),Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:const Row(children:[Icon(Icons.info_outline_rounded,color:green),SizedBox(width:10),Expanded(child:Text('Each person keeps their own Gmail and password. Only the OrgConnect role and organization access changes.',style:TextStyle(color:muted,height:1.4)))])),const SizedBox(height:22),const Text('Members',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900,color:dark)),const SizedBox(height:10),...members.asMap().entries.map((e)=>_card(e.value,e.key))])));}
  Widget _sum(String n,String l)=>Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(n,style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),Text(l,style:const TextStyle(color:Colors.white70,fontSize:11))]));
  Widget _card(Map<String,dynamic> m,int i){final p=m['profiles'];final x=p is Map?p:<String,dynamic>{};final role=x['role']?.toString()??'student',off=role=='officer',av=x['avatar_url']?.toString()??'';final name=x['name']?.toString().isNotEmpty==true?x['name'].toString():m['name']?.toString()??'Member';return Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:Row(children:[CircleAvatar(radius:25,backgroundColor:green.withOpacity(.1),backgroundImage:av.isNotEmpty?NetworkImage(av):null,child:av.isEmpty?const Icon(Icons.person_rounded,color:green):null),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(name,style:const TextStyle(fontWeight:FontWeight.w800,color:dark)),const SizedBox(height:3),Text(x['email']?.toString()??'No email linked',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:12,color:muted)),const SizedBox(height:6),Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:4),decoration:BoxDecoration(color:green.withOpacity(.1),borderRadius:BorderRadius.circular(20)),child:Text(off?'Officer':'Student',style:const TextStyle(fontSize:10,fontWeight:FontWeight.w800,color:green)))])),PopupMenuButton<String>(icon:const Icon(Icons.more_vert_rounded,color:green),onSelected:(v)=>changeRole(m,v),itemBuilder:(_)=>[if(!off)const PopupMenuItem(value:'officer',child:Text('Make Officer')),if(off)const PopupMenuItem(value:'student',child:Text('Return to Student'))]) ]));}
}
