import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../core/app_state.dart';
import '../Officer_Role/officer_members_screen.dart';
import '../Officer_Role/officer_org_profile_screen.dart';
import '../auth/unified_login_page.dart';
import 'adviser_profile_screen.dart';
import 'adviser_accounts_screen.dart';
import '../community/org_community_chat_screen.dart';
import '../analytics/event_comments_sheet.dart';

class AdviserDashboard extends StatefulWidget {
  final String orgId, orgName;
  const AdviserDashboard({super.key, required this.orgId, required this.orgName});
  @override State<AdviserDashboard> createState() => _AdviserDashboardState();
}

class _AdviserDashboardState extends State<AdviserDashboard> {
  static const green=Color(0xFF16A34A), dark=Color(0xFF12352A), muted=Color(0xFF6B8178), bg=Color(0xFFF3FAF5);
  final _db=Supabase.instance.client; int _tab=0; bool _loading=true;
  List<Map<String,dynamic>> _requests=[], _events=[], _members=[] ,_posts=[];

  @override void initState(){super.initState(); AppState.instance.setRole(UserRole.adviser); AppState.instance.setCurrentOfficerOrgId(widget.orgId); _load();}
  Future<void> _load() async { if(mounted)setState(()=>_loading=true); try{
    final results=await Future.wait([
      _db.from('event_requests').select('*').eq('org_id',widget.orgId).order('created_at',ascending:false),
      _db.from('events').select('*').eq('org_id',widget.orgId).order('date',ascending:false),
      _db.from('members').select('id,name,position,profile_id,profiles(name,active,avatar_url)').eq('org_id',widget.orgId),
      _db.from('notifications').select('id,title,message,date,created_at').eq('org_id',widget.orgId).isFilter('student_id',null).order('created_at',ascending:false),
    ]); if(!mounted)return; setState(() { _requests=List<Map<String,dynamic>>.from(results[0] as List); _events=List<Map<String,dynamic>>.from(results[1] as List); _members=List<Map<String,dynamic>>.from(results[2] as List); _posts=List<Map<String,dynamic>>.from(results[3] as List); _loading=false; });
  }catch(e){if(mounted){setState(()=>_loading=false);_snack('Unable to load adviser dashboard: $e',true);}} }
  void _snack(String s,[bool err=false])=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s),backgroundColor:err?Colors.red:green));
  String _date(dynamic v){final d=DateTime.tryParse('${v??''}');return d==null?'No date':'${d.month}/${d.day}/${d.year} • ${d.hour.toString().padLeft(2,'0')}:${d.minute.toString().padLeft(2,'0')}';}
  List<String> _images(Map<String,dynamic> r){final x=r['image_urls']; final y=r['creative_urls']; return [...(x is List?x.whereType<String>():<String>[]),...(y is List?y.whereType<String>():<String>[])];}

  Future<void> _forward(Map<String,dynamic> r) async {try{await _db.from('event_requests').update({'status':'forwarded_to_admin','adviser_reviewed_at':DateTime.now().toIso8601String(),'reviewed_by':_db.auth.currentUser?.id}).eq('id',r['id']);_snack('Proposal forwarded to Admin / CSO.');await _load();}catch(e){_snack('Could not forward proposal: $e',true);}}
  Future<void> _requestRevision(Map<String,dynamic> r) async {final f=await _feedback('Request Revision','Tell the officers what needs improvement.');if(f==null)return;try{await _db.from('event_requests').update({'status':'revision_requested','feedback':f,'adviser_reviewed_at':DateTime.now().toIso8601String(),'reviewed_by':_db.auth.currentUser?.id}).eq('id',r['id']);_snack('Revision sent back to officers.');await _load();}catch(e){_snack('Could not request revision: $e',true);}}
  Future<void> _publish(Map<String,dynamic> r) async {try{final imgs=_images(r);await _db.from('events').insert({'title':r['title'],'date':r['date'],'description':r['description']??'','org_name':widget.orgName,'org_id':widget.orgId,'image_url':imgs.isEmpty?null:imgs.first,'image_urls':imgs});await _db.from('event_requests').update({'status':'published','published_at':DateTime.now().toIso8601String(),'adviser_reviewed_at':DateTime.now().toIso8601String(),'reviewed_by':_db.auth.currentUser?.id}).eq('id',r['id']);await _db.from('notifications').insert({'id':DateTime.now().microsecondsSinceEpoch.toString(),'title':'New Event','message':'${r['title']} has been published by ${widget.orgName}.','date':DateTime.now().toIso8601String(),'read':false,'org_id':widget.orgId,'student_id':null});_snack('Event published successfully.');await _load();}catch(e){_snack('Could not publish event: $e',true);}}
  Future<String?> _feedback(String title,String hint) async {final c=TextEditingController();return showDialog<String>(context:context,builder:(x)=>AlertDialog(title:Text(title),content:TextField(controller:c,maxLines:4,decoration:InputDecoration(labelText:'Feedback',hintText:hint)),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(x,c.text.trim().isEmpty?'Please revise the submission.':c.text.trim()),child:const Text('Send'))]));}
  Future<void> _postAnnouncement() async {final t=TextEditingController(),m=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(x)=>AlertDialog(title:const Text('New Organization Announcement'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:t,decoration:const InputDecoration(labelText:'Title')),const SizedBox(height:10),TextField(controller:m,maxLines:5,decoration:const InputDecoration(labelText:'Announcement'))]),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('Post'))]));if(ok!=true||t.text.trim().isEmpty||m.text.trim().isEmpty)return;try{await _db.from('notifications').insert({'id':DateTime.now().microsecondsSinceEpoch.toString(),'title':t.text.trim(),'message':m.text.trim(),'date':DateTime.now().toIso8601String(),'read':false,'org_id':widget.orgId,'student_id':null});_snack('Announcement posted.');await _load();}catch(e){_snack('Could not post announcement: $e',true);}}

  @override Widget build(BuildContext context){return Scaffold(backgroundColor:bg,body:_loading?const Center(child:CircularProgressIndicator()):_tab==0?_home():_tab==1?_proposals():_tab==2?_org():_tab==3?_chat():_tab==4?AdviserAccountsScreen(orgId:widget.orgId,orgName:widget.orgName):const AdviserProfileScreen(),bottomNavigationBar:_nav());}
  Widget _nav()=>Container(decoration:BoxDecoration(color:Colors.white,boxShadow:[BoxShadow(color:Colors.black.withOpacity(.08),blurRadius:18,offset:const Offset(0,-5))]),child:SafeArea(top:false,child:NavigationBar(height:72,backgroundColor:Colors.white,indicatorColor:green.withOpacity(.12),selectedIndex:_tab,onDestinationSelected:(i)=>setState(()=>_tab=i),destinations:[const NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home_rounded,color:green),label:'Home'),NavigationDestination(icon:Badge(label:_requests.any((r)=>r['status']=='admin_approved'||r['status']=='creative_submitted')?const Text('!'):null,child:Icon(Icons.assignment_outlined)),selectedIcon:Icon(Icons.assignment_rounded,color:green),label:'Proposals'),const NavigationDestination(icon:Icon(Icons.apartment_outlined),selectedIcon:Icon(Icons.apartment_rounded,color:green),label:'Organization'),const NavigationDestination(icon:Icon(Icons.forum_outlined),selectedIcon:Icon(Icons.forum_rounded,color:green),label:'Community'),NavigationDestination(icon:Icon(Icons.manage_accounts_outlined),selectedIcon:Icon(Icons.manage_accounts_rounded,color:green),label:'Accounts'),const NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person_rounded,color:green),label:'Profile')])));
  Widget _chat()=>OrgCommunityChatScreen(orgId:widget.orgId,orgName:widget.orgName,showBackButton:false);
  Widget _page(String title,String subtitle,List<Widget> children)=>SafeArea(child:RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.fromLTRB(18,20,18,30),children:[Text(title,style:const TextStyle(fontSize:29,fontWeight:FontWeight.w900,color:dark)),const SizedBox(height:4),Text(subtitle,style:const TextStyle(color:muted)),const SizedBox(height:20),...children])));
  Widget _home()=>_page('Good day, Adviser 👋','Everything happening in ${widget.orgName}, in one place.',[
    Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:const LinearGradient(colors:[green,Color(0xFF0F766E)]),borderRadius:BorderRadius.circular(24)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Organization pulse',style:TextStyle(color:Colors.white70,fontWeight:FontWeight.w600)),const SizedBox(height:5),Text(widget.orgName,style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:16),Row(children:[_mini('${_events.length}','Published events'),_mini('${_members.length}','Members'),_mini('${_members.where((m){final p=m['profiles'];return p is Map&&p['active']==true;}).length}','Active')])])),
    const SizedBox(height:18),
    Row(children:[Expanded(child:_stat(Icons.assignment_outlined,'Proposals',_requests.where((r)=>r['status']!='published').length)),const SizedBox(width:12),Expanded(child:_stat(Icons.campaign_outlined,'Announcements',_posts.length))]),
    const SizedBox(height:22),
    Row(children:[const Expanded(child:Text('Published Events',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800,color:dark))),TextButton(onPressed:()=>setState(()=>_tab=1),child:const Text('Workflow'))]),
    if(_events.isEmpty)_empty('No published events yet. Approved event creatives will appear here.') else ..._events.take(6).map(_eventCard),
    const SizedBox(height:18),
    Row(children:[const Expanded(child:Text('Member Activity',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800,color:dark))),TextButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const OfficerMembersScreen())),child:const Text('View all'))]),
    _memberCard(),
    const SizedBox(height:18),_sectionTitle('Announcements'),
    ..._posts.take(3).map((p)=>_postCard(p)),
    if(_posts.isEmpty)_empty('No announcements yet.'),
    const SizedBox(height:12),FilledButton.icon(onPressed:_postAnnouncement,icon:const Icon(Icons.add_rounded),label:const Text('Create Announcement'),style:FilledButton.styleFrom(backgroundColor:green,padding:const EdgeInsets.symmetric(vertical:15),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(14))))
  ]);
  Widget _proposals()=>_page('Proposal Center','Follow every activity from the first idea to the final published event.',[
    Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:const LinearGradient(colors:[green,Color(0xFF0F766E)]),borderRadius:BorderRadius.circular(24)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
      Row(children:[Container(padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:Colors.white.withOpacity(.16),borderRadius:BorderRadius.circular(14)),child:const Icon(Icons.route_rounded,color:Colors.white)),const SizedBox(width:12),const Expanded(child:Text('Activity approval journey',style:TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w800)))]),
      const SizedBox(height:16),
      const Text('Proposal → Admin / CSO → Creative → Adviser Review → Publish',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w700)),
      const SizedBox(height:8),const Text('Written proposals are kept separate from final posters and event announcements.',style:TextStyle(color:Colors.white70,height:1.35))
    ])),
    const SizedBox(height:16),
    Row(children:[Expanded(child:_proposalStat('Waiting for you',_requests.where((r)=>r['status']=='pending'||r['status']=='creative_submitted').length,Icons.pending_actions_rounded)),const SizedBox(width:10),Expanded(child:_proposalStat('With Admin',_requests.where((r)=>r['status']=='forwarded_to_admin').length,Icons.admin_panel_settings_outlined)),const SizedBox(width:10),Expanded(child:_proposalStat('Published',_requests.where((r)=>r['status']=='published').length,Icons.verified_rounded))]),
    const SizedBox(height:20),
    Row(children:[const Expanded(child:Text('All proposals',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900,color:dark))),Text('${_requests.length} total',style:const TextStyle(color:muted,fontWeight:FontWeight.w700))]),
    const SizedBox(height:10),
    ..._requests.map(_proposalCard), if(_requests.isEmpty)_empty('No proposals have been submitted by officers yet.')
  ]);
  Widget _proposalStat(String label,int n,IconData icon)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.035),blurRadius:12,offset:const Offset(0,4))]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,color:green),const SizedBox(height:8),Text('$n',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900,color:dark)),Text(label,style:const TextStyle(fontSize:10,color:muted,fontWeight:FontWeight.w700))]));
  Widget _proposalCard(Map<String,dynamic> r){final s='${r['status']??'pending'}';final imgs=_images(r);return Container(margin:const EdgeInsets.only(bottom:14),padding:const EdgeInsets.all(17),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.04),blurRadius:14,offset:const Offset(0,5))]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(r['title']?.toString()??'Untitled proposal',style:const TextStyle(fontSize:17,fontWeight:FontWeight.w800,color:dark))),_chip(s)]),const SizedBox(height:8),Text(r['description']?.toString()??'',style:const TextStyle(color:muted,height:1.45)),const SizedBox(height:8),Text('Proposed date: ${_date(r['date'])}',style:const TextStyle(fontWeight:FontWeight.w700,color:dark)),if((r['feedback']??'').toString().isNotEmpty)_feedbackBox('Adviser feedback',r['feedback'].toString()),if((r['admin_feedback']??'').toString().isNotEmpty)_feedbackBox('Admin / CSO feedback',r['admin_feedback'].toString()),if(imgs.isNotEmpty)...[const SizedBox(height:12),SizedBox(height:150,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:imgs.length,separatorBuilder:(_,__)=>const SizedBox(width:8),itemBuilder:(_,i)=>ClipRRect(borderRadius:BorderRadius.circular(14),child:Image.network(imgs[i],width:190,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(width:190,color:bg,child:const Icon(Icons.broken_image))))))],const SizedBox(height:14),_actions(r,s)]));}
  Widget _actions(Map<String,dynamic> r,String s){if(s=='pending')return Row(children:[Expanded(child:OutlinedButton.icon(onPressed:()=>_requestRevision(r),icon:const Icon(Icons.edit_note),label:const Text('Ask Officer to Revise'))),const SizedBox(width:8),Expanded(child:FilledButton.icon(onPressed:()=>_forward(r),icon:const Icon(Icons.forward_rounded),label:const Text('Forward to Admin')))]);if(s=='admin_approved')return const Text('Admin/CSO approved this proposal. Officers can now prepare the final poster/photos and send them back here.',style:TextStyle(color:green,fontWeight:FontWeight.w700));if(s=='creative_submitted')return Row(children:[Expanded(child:OutlinedButton.icon(onPressed:()=>_requestRevision(r),icon:const Icon(Icons.rate_review_outlined),label:const Text('Request Revision'))),const SizedBox(width:8),Expanded(child:FilledButton.icon(onPressed:()=>_publish(r),icon:const Icon(Icons.publish_rounded),label:const Text('Approve & Publish')))]);if(s=='revision_requested')return const Text('Revision requested. Waiting for officers to resubmit the improved creative.',style:TextStyle(color:Color(0xFFB45309),fontWeight:FontWeight.w700));if(s=='forwarded_to_admin')return const Text('Waiting for Admin / CSO decision.',style:TextStyle(color:muted,fontWeight:FontWeight.w700));return const SizedBox.shrink();}
  Widget _org()=>_page('Organization','Keep your organization identity, information, and branding polished.',[
    Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF14532D),green],begin:Alignment.topLeft,end:Alignment.bottomRight),borderRadius:BorderRadius.circular(26)),child:Row(children:[Container(width:64,height:64,decoration:BoxDecoration(color:Colors.white.withOpacity(.16),borderRadius:BorderRadius.circular(20)),child:const Icon(Icons.apartment_rounded,color:Colors.white,size:34)),const SizedBox(width:16),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('YOUR ORGANIZATION',style:TextStyle(color:Colors.white70,fontSize:10,fontWeight:FontWeight.w800,letterSpacing:1.2)),const SizedBox(height:4),Text(widget.orgName,style:const TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:4),const Text('Organization profile & branding',style:TextStyle(color:Colors.white70))]))])),
    const SizedBox(height:16),
    Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.04),blurRadius:16,offset:const Offset(0,5))]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Make your organization stand out',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900,color:dark)),const SizedBox(height:6),const Text('Update the information members see and keep your visual identity consistent across OrgConnect.',style:TextStyle(color:muted,height:1.4)),const SizedBox(height:16),FilledButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>OfficerOrgProfileScreen(orgId:widget.orgId))).then((_){setState((){});}),icon:const Icon(Icons.auto_awesome_rounded),label:const Text('Edit Organization Profile'),style:FilledButton.styleFrom(backgroundColor:green,minimumSize:const Size(double.infinity,52),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(15))))])),
    const SizedBox(height:18),
    const Text('Organization details',style:TextStyle(fontSize:19,fontWeight:FontWeight.w900,color:dark)),const SizedBox(height:10),
    Row(children:[Expanded(child:_orgFeature(Icons.badge_outlined,'Identity','Name, acronym & category')),const SizedBox(width:10),Expanded(child:_orgFeature(Icons.auto_awesome_outlined,'Branding','Logo & activity highlights'))]),const SizedBox(height:10),
    Row(children:[Expanded(child:_orgFeature(Icons.menu_book_outlined,'About','Description & mission')),const SizedBox(width:10),Expanded(child:_orgFeature(Icons.link_rounded,'Contact','Social & contact links'))])
  ]);
  Widget _orgFeature(IconData icon,String title,String text)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:green.withOpacity(.1),borderRadius:BorderRadius.circular(11)),child:Icon(icon,color:green,size:21)),const SizedBox(height:10),Text(title,style:const TextStyle(fontWeight:FontWeight.w800,color:dark)),const SizedBox(height:3),Text(text,style:const TextStyle(fontSize:11,color:muted,height:1.3))]));
  Widget _memberCard(){final active=_members.where((m){final p=m['profiles'];return p is Map&&p['active']==true;}).length;return Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:Row(children:[_avatar(''),const SizedBox(width:12),Expanded(child:Text('$active active • ${_members.length-active} inactive',style:const TextStyle(fontWeight:FontWeight.w700,color:dark))),TextButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const OfficerMembersScreen())),child:const Text('Manage'))]));}
  Widget _eventCard(Map<String,dynamic> e){final imgs=(e['image_urls'] is List?e['image_urls']:<dynamic>[]).whereType<String>().toList();final url=e['image_url']?.toString();if(url!=null&&url.isNotEmpty&&!imgs.contains(url))imgs.insert(0,url);return Container(margin:const EdgeInsets.only(bottom:14),clipBehavior:Clip.antiAlias,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(imgs.isNotEmpty)SizedBox(height:170,width:double.infinity,child:Image.network(imgs.first,fit:BoxFit.cover,errorBuilder:(_,__,___)=>_imagePlaceholder()))else _imagePlaceholder(),Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(e['title']?.toString()??'',style:const TextStyle(fontSize:17,fontWeight:FontWeight.w800,color:dark)),const SizedBox(height:5),Text(_date(e['date']),style:const TextStyle(color:green,fontWeight:FontWeight.w700)),const SizedBox(height:6),Text(e['description']?.toString()??'',maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:muted)),const SizedBox(height:10),Align(alignment:Alignment.centerRight,child:TextButton.icon(onPressed:()=>showEventComments(context,eventId:e['id'].toString(),eventTitle:e['title']?.toString()??'Event'),icon:const Icon(Icons.forum_outlined,color:green),label:const Text('View Comments',style:TextStyle(color:green))))]))]));}
  Widget _postCard(Map<String,dynamic> p)=>Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p['title']?.toString()??'',style:const TextStyle(fontWeight:FontWeight.w800,color:dark)),const SizedBox(height:5),Text(p['message']?.toString()??'',style:const TextStyle(color:muted,height:1.4))]));
  Widget _feedbackBox(String t,String x)=>Container(width:double.infinity,margin:const EdgeInsets.only(top:10),padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:const Color(0xFFFFFBEB),borderRadius:BorderRadius.circular(12)),child:Text('$t: $x',style:const TextStyle(color:Color(0xFF92400E))));
  Widget _stat(IconData i,String l,int n)=>Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:Row(children:[Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:green.withOpacity(.1),borderRadius:BorderRadius.circular(12)),child:Icon(i,color:green)),const SizedBox(width:10),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('$n',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900,color:dark)),Text(l,style:const TextStyle(fontSize:11,color:muted))])]));
  Widget _mini(String n,String l)=>Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(n,style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),Text(l,style:const TextStyle(color:Colors.white70,fontSize:11))]));
  Widget _sectionTitle(String t)=>Text(t,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800,color:dark));
  Widget _bullet(String t)=>Padding(padding:const EdgeInsets.only(bottom:9),child:Row(children:[const Icon(Icons.check_circle_rounded,color:green,size:18),const SizedBox(width:8),Expanded(child:Text(t,style:const TextStyle(color:muted)))]));
  Widget _avatar(String url)=>CircleAvatar(radius:23,backgroundColor:green.withOpacity(.12),backgroundImage:url.isNotEmpty?NetworkImage(url):null,child:url.isEmpty?const Icon(Icons.person,color:green):null);
  Widget _imagePlaceholder()=>Container(height:170,color:green.withOpacity(.06),child:const Center(child:Icon(Icons.image_outlined,color:green,size:44)));
  Widget _empty(String t)=>Container(padding:const EdgeInsets.all(24),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:Center(child:Text(t,textAlign:TextAlign.center,style:const TextStyle(color:muted,height:1.45))));
  Widget _chip(String s){Color c=s=='published'||s=='admin_approved'?green:s=='admin_rejected'?Colors.red:s=='creative_submitted'?const Color(0xFF2563EB):s=='revision_requested'?const Color(0xFFD97706):muted;return Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:5),decoration:BoxDecoration(color:c.withOpacity(.1),borderRadius:BorderRadius.circular(30)),child:Text(s.replaceAll('_',' ').toUpperCase(),style:TextStyle(color:c,fontSize:9,fontWeight:FontWeight.w900)));}
  @override void dispose(){super.dispose();}
}
