import 'dart:typed_data';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class OfficerEventsScreen extends StatefulWidget {
  final String orgId, orgName;
  const OfficerEventsScreen({super.key, required this.orgId, required this.orgName});
  @override State<OfficerEventsScreen> createState()=>_OfficerEventsScreenState();
}
class _OfficerEventsScreenState extends State<OfficerEventsScreen>{
  static const green=Color(0xFF16A34A), bg=Color(0xFFF0FDF4), dark=Color(0xFF12352A), muted=Color(0xFF64748B);
  final _db=Supabase.instance.client; List<Map<String,dynamic>> _requests=[]; bool _loading=true;
  @override void initState(){super.initState();_load();}
  Future<void> _load() async {setState(()=>_loading=true);try{final rows=await _db.from('event_requests').select('*').eq('org_id',widget.orgId).order('created_at',ascending:false);if(mounted)setState(() { _requests=List<Map<String,dynamic>>.from(rows as List); _loading=false; });}catch(e){if(mounted){setState(()=>_loading=false);_snack('Unable to load proposals: $e',true);}}}
  Future<void> _createRequest() async {final title=TextEditingController(),desc=TextEditingController();DateTime selected=DateTime.now().add(const Duration(days:1));final result=await showDialog<bool>(context:context,builder:(ctx)=>StatefulBuilder(builder:(ctx,ss)=>AlertDialog(title:const Text('New Activity Proposal'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:title,decoration:const InputDecoration(labelText:'Proposed activity',hintText:'Intramurals Opening Program')),const SizedBox(height:12),TextField(controller:desc,maxLines:5,decoration:const InputDecoration(labelText:'Proposal details',hintText:'Explain what the organization plans to do, purpose, expected participants, venue and needed resources.')),const SizedBox(height:12),ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.calendar_today,color:green),title:const Text('Target date'),subtitle:Text(_date(selected)),onTap:()async{final p=await showDatePicker(context:ctx,initialDate:selected,firstDate:DateTime.now(),lastDate:DateTime.now().add(const Duration(days:365)));if(p!=null)ss(()=>selected=p);})])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('Submit Proposal'))])));if(result!=true||title.text.trim().isEmpty||desc.text.trim().isEmpty)return;try{await _db.from('event_requests').insert({'id':DateTime.now().microsecondsSinceEpoch.toString(),'org_id':widget.orgId,'requested_by':_db.auth.currentUser?.id,'title':title.text.trim(),'date':selected.toIso8601String(),'description':desc.text.trim(),'image_urls':<String>[],'creative_urls':<String>[],'status':'pending'});_snack('Proposal sent to the adviser.');await _load();}catch(e){_snack('Could not submit proposal: $e',true);}}
  Future<void> _submitCreative(Map<String,dynamic> r) async {final files=await FilePicker.platform.pickFiles(type:FileType.image,allowMultiple:true,withData:true);if(files==null)return;final urls=<String>[];try{for(final f in files.files){if(f.bytes==null)continue;final ext=f.extension??'jpg';final path='event_creatives/${widget.orgId}/${r['id']}_${DateTime.now().microsecondsSinceEpoch}.$ext';await _db.storage.from('org-assets').uploadBinary(path,f.bytes!,fileOptions:FileOptions(contentType:'image/$ext',upsert:true));urls.add(_db.storage.from('org-assets').getPublicUrl(path));}if(urls.isEmpty)return;await _db.from('event_requests').update({'creative_urls':urls,'status':'creative_submitted','submitted_at':DateTime.now().toIso8601String(),'updated_at':DateTime.now().toIso8601String()}).eq('id',r['id']);_snack('Final creative sent to the adviser for review.');await _load();}catch(e){_snack('Could not upload creative: $e',true);}}
  Future<void> _revise(Map<String,dynamic> r) async {final t=TextEditingController(text:r['description']?.toString()??'');final ok=await showDialog<bool>(context:context,builder:(x)=>AlertDialog(title:const Text('Revise Proposal'),content:TextField(controller:t,maxLines:6,decoration:const InputDecoration(labelText:'Updated details')),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('Resubmit'))]));if(ok==true&&t.text.trim().isNotEmpty){await _db.from('event_requests').update({'description':t.text.trim(),'status':'pending','feedback':''}).eq('id',r['id']);_snack('Proposal resubmitted to adviser.');await _load();}}
  String _date(dynamic v){final d=DateTime.tryParse('${v??''}');return d==null?'No date':'${d.year}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}';}
  void _snack(String s,[bool err=false])=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s),backgroundColor:err?Colors.red:green));
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:bg,appBar:AppBar(backgroundColor:green,foregroundColor:Colors.white,title:const Text('Activity Proposals')),body:_loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.all(18),children:[Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:const Text('Step 1: submit a written proposal. After Admin/CSO approval, Step 2 unlocks so you can create an eye-catching poster/photos and send them to your adviser.',style:TextStyle(color:dark,height:1.45,fontWeight:FontWeight.w600))),const SizedBox(height:16),..._requests.map(_card),if(_requests.isEmpty)const Padding(padding:EdgeInsets.all(40),child:Center(child:Text('No proposals yet.')))])),floatingActionButton:FloatingActionButton.extended(backgroundColor:green,foregroundColor:Colors.white,onPressed:_createRequest,icon:const Icon(Icons.add),label:const Text('New Proposal')));
  Widget _card(Map<String,dynamic> r){final s=r['status']?.toString()??'pending';final imgs=(r['creative_urls'] is List?r['creative_urls']:<dynamic>[]).whereType<String>().toList();return Container(margin:const EdgeInsets.only(bottom:14),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(r['title']?.toString()??'',style:const TextStyle(fontSize:17,fontWeight:FontWeight.w800,color:dark))),_chip(s)]),const SizedBox(height:7),Text(r['description']?.toString()??'',style:const TextStyle(color:muted,height:1.45)),const SizedBox(height:6),Text('Target: ${_date(r['date'])}',style:const TextStyle(fontWeight:FontWeight.w700,color:dark)),if((r['feedback']??'').toString().isNotEmpty)Padding(padding:const EdgeInsets.only(top:8),child:Text('Adviser feedback: ${r['feedback']}',style:const TextStyle(color:Colors.red))),if((r['admin_feedback']??'').toString().isNotEmpty)Padding(padding:const EdgeInsets.only(top:8),child:Text('Admin/CSO feedback: ${r['admin_feedback']}',style:const TextStyle(color:Colors.red))),if(imgs.isNotEmpty)Padding(padding:const EdgeInsets.only(top:12),child:SizedBox(height:130,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:imgs.length,separatorBuilder:(_,__)=>const SizedBox(width:8),itemBuilder:(_,i)=>ClipRRect(borderRadius:BorderRadius.circular(12),child:Image.network(imgs[i],width:170,fit:BoxFit.cover))))),const SizedBox(height:12),if(s=='admin_approved'||s=='revision_requested')FilledButton.icon(onPressed:()=>_submitCreative(r),icon:const Icon(Icons.image_outlined),label:Text(s=='revision_requested'?'Improve & Resubmit Creative':'Create & Send Final Creative'),style:FilledButton.styleFrom(backgroundColor:green)),if(s=='rejected'||s=='admin_rejected'||s=='revision_requested'&&((r['creative_urls']??[]) as List).isEmpty&&false)const SizedBox.shrink()]));}
  Widget _chip(String s){final c=s=='admin_approved'||s=='creative_submitted'?green:s=='admin_rejected'?Colors.red:s=='revision_requested'?Colors.orange:muted;return Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:5),decoration:BoxDecoration(color:c.withOpacity(.1),borderRadius:BorderRadius.circular(30)),child:Text(s.replaceAll('_',' ').toUpperCase(),style:TextStyle(color:c,fontSize:9,fontWeight:FontWeight.w800)));}
}
