/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rocilmanliguez;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author manli
 */
public class StudentForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentForm.class.getName());

    /**
     * Creates new form StudentForm
     */
    public StudentForm() {
        initComponents();
        setTitle("Student Information Form");
        setSize(400, 320);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        courseBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        yearBox = new javax.swing.JComboBox<>();
        submitBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setText("Name:");
        getContentPane().add(jLabel1);
        getContentPane().add(nameField);

        jLabel2.setText("Age:");
        getContentPane().add(jLabel2);
        getContentPane().add(ageField);

        jLabel3.setText("Gender:");
        getContentPane().add(jLabel3);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        maleRadio.setForeground(new java.awt.Color(255, 255, 255));
        maleRadio.setText("Male");

        femaleRadio.setForeground(new java.awt.Color(255, 255, 255));
        femaleRadio.setText("Female");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(maleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(femaleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleRadio)
                    .addComponent(femaleRadio))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jLabel4.setText("Course:");
        getContentPane().add(jLabel4);

        courseBox.setBackground(new java.awt.Color(0, 0, 0));
        courseBox.setForeground(new java.awt.Color(255, 255, 255));
        courseBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select Course>", "BSIT", "BSCS", "BSIS", "BSCE" }));
        getContentPane().add(courseBox);

        jLabel5.setText("Year level:");
        getContentPane().add(jLabel5);

        yearBox.setBackground(new java.awt.Color(0, 0, 0));
        yearBox.setForeground(new java.awt.Color(255, 255, 255));
        yearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select Year level>", "1st year", "2nd year", "3rd year", "4th year" }));
        getContentPane().add(yearBox);

        submitBtn.setBackground(new java.awt.Color(0, 0, 0));
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(submitBtn);

        clearBtn.setBackground(new java.awt.Color(0, 0, 0));
        clearBtn.setForeground(new java.awt.Color(255, 0, 0));
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:

        nameField.setText("");

        ageField.setText("");

        maleRadio.setSelected(false);

        femaleRadio.setSelected(false);

        courseBox.setSelectedIndex(0);

        yearBox.setSelectedIndex(0);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String name = nameField.getText().trim();

        String age = ageField.getText().trim();

        String gender = maleRadio.isSelected() ? "Male" : femaleRadio.isSelected() ? "Female" : "Not selected";

        String course = (String) courseBox.getSelectedItem();

        String year = (String) yearBox.getSelectedItem();

// Simple validation
        if (name.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Please enter the name.", "Input error", JOptionPane.WARNING_MESSAGE);

            return;

        }

        if (age.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Please enter the age.", "Input error", JOptionPane.WARNING_MESSAGE);
            return;

        }

        String message = String.format(
                "Student Information:\nName: %s\nAge: %s\nGender: %s\nCourse: %s\nYear Level: %s",
                name, age, gender, course, year
        );

        JOptionPane.showMessageDialog(this, message, "Student Info", JOptionPane.INFORMATION_MESSAGE);

        // TODO add your handling code here:

    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JButton clearBtn;
    private javax.swing.JComboBox<String> courseBox;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JComboBox<String> yearBox;
    // End of variables declaration//GEN-END:variables
}
